name: Deploy to production
on:
  push:
    branches:
      - master
jobs:
  deploy_production:
    name: Deploy the updated code to production
    runs-on: ubuntu-latest
    needs: execute_tests
    steps:
      - name: Pull code and restart server
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            key: ${{ secrets.KEY }}
            script: |
                cd /home/ubuntu/polls/polls
                git checkout -- *
                git checkout master
                git pull origin master
                sudo kill $(ps aux | grep gunicorn | grep -v grep | awk '{print $2}')
                sudo /home/ubuntu/polls/.venv/bin/gunicorn --daemon --workers=4 mysite.wsgi:application -b 0.0.0.0:80
      - name: Pull code and restart server 2
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST_2 }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            key: ${{ secrets.KEY }}
            script: |
                cd /home/ubuntu/polls/polls
                git checkout -- *
                git checkout master
                git pull origin master
                sudo kill $(ps aux | grep gunicorn | grep -v grep | awk '{print $2}')
                sudo /home/ubuntu/polls/.venv/bin/gunicorn --daemon --workers=4 mysite.wsgi:application -b 0.0.0.0:80
