name: Pull request on staging
on:
  pull_request:
    types: [opened]
    branches:
      - staging
jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Start mysql
        run: sudo systemctl start mysql.service
      - name: Update package list
        run: sudo apt update
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Copy environment file
        run: cp .env.ci .env
      - name: Check style guide and conventions
        run: pycodestyle .
      - name: Execute tests
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings
        run: pytest
