name: Pull request on any bramch v1
on: push
jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Update package list
        run: sudo apt update
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Copy environment file
        run: cp .env.ci .env
      - name: Execute tests
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings
        run: pytest